### ISSUE TITLE
content error when contain tabview

### ISSUE THREAD

**Issue by huongtran84** [fermoya/SwiftUIMenu#4]
When my content contain tabview .i could not click on tabitem

**Comment by fermoya** [comment]
Hi,

Can you share your code, Xcode version and SwiftUIMenu version, please? It's working for me:
```
var body: some View {
    TabView {
        menu.tabItem { Text("Tab 1") }
        Text("Another Tab").tabItem { Text("Tab 2") }
    }
}

var menu: some View {
    NavigationView {
        Menu(...)
    }
}
```
And the result:
![simulator](https://user-images.githubusercontent.com/11335612/77150870-bbfb5d80-6a8c-11ea-9a06-4a81dbf307e7.gif)
Have in mind that `Menu` should be used as a tab, not to wrap `TabView`.

**Comment by huongtran84** [comment]
thanks for your reply.in my case.I want to menu contains 2 tabs.click on tab 2 menubutton still exist to open and close menu.any suggest?

**Comment by fermoya** [comment]
Hi @huongtran84 ,

I released version 1.1.1. Try this version and call `disableContentTap`. It should work like that.

![simulator](https://user-images.githubusercontent.com/11335612/77414530-1c560c00-6db9-11ea-939b-dd0c218d5af6.gif)

**Comment by huongtran84** [comment]
Hi.I face a bug that each close or open menu content view always reload .what is way prevent it?

**Comment by fermoya** [comment]
Hi @huongtran84 ,

Please, open a new issue for that. Have in mind that in SwiftUI, Views get redrawn when a state variable changes. In this case, Menu has several bindings and states that will trigger an update, that's right.

Let me know if this thread is closed as I'd like to close it.

Thanks
