### ISSUE TITLE
could not change to another segmented 

### ISSUE THREAD

**Issue by huongtran84** [fermoya/SwiftUIMenu#6]
Content of menu contain Picker I could click on another item.here is full code

import SwiftUI

struct ContentView: View {

    @State var index = 0
    @State var isMenuOpen = false
    var isMenuOnLeft = true
    var strengths = ["Mild", "Medium", "Mature"]

    @State private var selectedStrength = 0

    var body: some View {
        NavigationView {
           
            Menu(indexSelected: self.$index,
                 isOpen: self.$isMenuOpen,
                 menuItems: menuItems,
                 id: \.name,
                 menuItemRow: {
                    Text($0.name)
                        .foregroundColor($0.color)
            },
                 menuItemContent: { section in
                    ZStack {
                      Rectangle().fill(menuItems[self.index].color)

                                Picker(selection: self.$selectedStrength, label: Text("Strength")) {
                                    ForEach(0 ..< self.strengths.count) {
                                        Text(self.strengths[$0])

                                    }
                        }.pickerStyle(SegmentedPickerStyle())
                            
                        
                       
                    }
                    .navigationBarItems(leading: self.isMenuOnLeft ? AnyView(self.menuButton) : AnyView(EmptyView()),
                                        trailing: self.isMenuOnLeft ? AnyView(EmptyView()) : AnyView(self.menuButton))
                        .navigationBarTitle(Text("SwiftUIMenu"), displayMode: .inline)
            }).style(.stretch)
                .revealRatio(0.8)
                .header(header: {
                    ProfileHeader()
                })
                .alignment(isMenuOnLeft ? .left : .right)
                .footer(footer: {
                    Text("Copyright © 2020 Fernando Moya de Rivas. All rights reserved.")
                })
                .shadeContent()
                .edgesIgnoringSafeArea(.top)
        }.onAppear {
            UITableView.appearance().separatorStyle = .none
        }
    }
}

extension ContentView {

    var menuButton: some View {
        Button(action: {
            withAnimation {
                self.isMenuOpen.toggle()
            }
        }) {
            Image(systemName: self.isMenuOpen ? "xmark" : "list.bullet")
                .padding()
        }
    }

}

**Comment by fermoya** [comment]
Hi,

You need to call `disableContentTap()`. I'm gonna make a quick release to set this behaviour as default.

![simulator](https://user-images.githubusercontent.com/11335612/78153311-d4775a80-7432-11ea-9fe7-6dbeec354806.gif)

Thanks

**Comment by fermoya** [comment]
Use version `1.1.2` so that by default `allowsContentTap` is false. If you're still using an older version, please call `disableContentTap()`
